version: "3.8"

services:
  app:
    build: .
    container_name: flask_app

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx_waf
    ports:
      - "8080:80"
    depends_on:
      - app

